export const RESUME_TEMPLATES = [
  {
    id: "minimal",
    name: "Minimal Clean",
    styleDirection: "simple",
    category: "simple",
    badge: "Minimalist",
    description: "Generous whitespace, clean typography, subtle hairline rules. Zero distraction, pure content clarity.",
    bestFor: "Frontend Engineers, UI/UX, Minimalists, Startups",
  },
  {
    id: "modern",
    name: "Modern Dynamic",
    styleDirection: "modern",
    category: "modern",
    badge: "Recruiter Favorite",
    description: "Contemporary layout with subtle colored accent indicators, split metadata headers, and clean pill tags.",
    bestFor: "Full-Stack Devs, Product Engineers, Tech Companies",
  },
  {
    id: "professional",
    name: "Corporate Standard",
    styleDirection: "professional",
    category: "professional",
    badge: "ATS Gold Standard",
    description: "Authoritative traditional corporate design with balanced hierarchy and conventional recruiter formatting.",
    bestFor: "Finance, Consulting, Enterprise Tech, Big Tech",
  },
  {
    id: "executive",
    name: "Executive Suite",
    styleDirection: "executive",
    category: "executive",
    badge: "Leadership & Senior",
    description: "Distinguished centered masthead, letterspaced serif headings, balanced luxury spacing and sophistication.",
    bestFor: "Staff+ Engineers, Tech Leads, Engineering Directors",
  },
  {
    id: "creative",
    name: "Creative Asymmetric",
    styleDirection: "creative",
    category: "creative",
    badge: "Distinctive Grid",
    description: "Tasteful two-column structure with an understated left sidebar for core competencies and contact details.",
    bestFor: "Design Technologists, Creative Developers, Product Designers",
  },
  {
    id: "technical",
    name: "Technical Matrix",
    styleDirection: "modern",
    category: "technical",
    badge: "Developer First",
    description: "Optimized for software engineers: highlights skill proficiencies, system architecture projects, and contest stats.",
    bestFor: "Backend, Systems, Algorithmic Coders, DevOps",
  },
  {
    id: "academic",
    name: "Academic & Research",
    styleDirection: "professional",
    category: "academic",
    badge: "Scholarly & Dense",
    description: "Structured, information-dense formal layout with scholarly hierarchy, credential emphasis, and clean double rules.",
    bestFor: "AI/ML Researchers, Data Scientists, PhDs, Academia",
  },
  {
    id: "elegant",
    name: "Timeless Elegant",
    styleDirection: "executive",
    category: "elegant",
    badge: "Editorial Luxury",
    description: "Editorial luxury with Cormorant Garamond serif headings, delicate accents, and balanced whitespace.",
    bestFor: "Specialist Roles, Boutique Consultancies, Strategy",
  },
];

export const STYLE_DIRECTIONS = [
  {
    id: "simple",
    name: "Simple",
    tagline: "Uncluttered, pure black & white, no decorative distractions.",
    defaultTemplate: "minimal",
    accentColor: "#111827",
    fontPairing: "modern-sans",
    dividerStyle: "hairline",
    headerLayout: "left",
    showIcons: false,
    sectionSpacing: "standard",
    margins: "generous",
  },
  {
    id: "modern",
    name: "Modern",
    tagline: "Contemporary typography, crisp colored accents, clean tags.",
    defaultTemplate: "modern",
    accentColor: "#4338ca",
    fontPairing: "modern-sans",
    dividerStyle: "accent-bar",
    headerLayout: "split",
    showIcons: true,
    sectionSpacing: "standard",
    margins: "standard",
  },
  {
    id: "professional",
    name: "Professional",
    tagline: "Conventional hiring-friendly structure, authoritative corporate styling.",
    defaultTemplate: "professional",
    accentColor: "#1e3a8a",
    fontPairing: "classic-serif",
    dividerStyle: "solid",
    headerLayout: "centered",
    showIcons: true,
    sectionSpacing: "standard",
    margins: "standard",
  },
  {
    id: "executive",
    name: "Executive",
    tagline: "Sophisticated serif typography, balanced whitespace, premium presence.",
    defaultTemplate: "executive",
    accentColor: "#881337",
    fontPairing: "executive-serif",
    dividerStyle: "double",
    headerLayout: "centered",
    showIcons: false,
    sectionSpacing: "spacious",
    margins: "generous",
  },
  {
    id: "creative",
    name: "Creative",
    tagline: "Distinctive two-column composition, tasteful personality, high impact.",
    defaultTemplate: "creative",
    accentColor: "#0f766e",
    fontPairing: "modern-sans",
    dividerStyle: "solid",
    headerLayout: "split",
    showIcons: true,
    sectionSpacing: "standard",
    margins: "compact",
  },
];

export const COLOR_PALETTES = [
  { id: "monochrome", name: "Black & White", hex: "#111827", lightBg: "#f3f4f6" },
  { id: "navy", name: "Classic Navy", hex: "#1e3a8a", lightBg: "#eff6ff" },
  { id: "slate", name: "Slate Charcoal", hex: "#334155", lightBg: "#f8fafc" },
  { id: "burgundy", name: "Deep Burgundy", hex: "#881337", lightBg: "#fff1f2" },
  { id: "forest", name: "Forest Green", hex: "#14532d", lightBg: "#f0fdf4" },
  { id: "teal", name: "Teal Ocean", hex: "#0f766e", lightBg: "#f0fdfa" },
  { id: "indigo", name: "Royal Indigo", hex: "#4338ca", lightBg: "#eef2ff" },
];

export const FONT_PAIRINGS = [
  {
    id: "modern-sans",
    name: "Modern Sans",
    description: "Plus Jakarta Sans + Inter",
    headingFont: "'Plus Jakarta Sans', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  {
    id: "classic-serif",
    name: "Classic Corporate",
    description: "Merriweather + Inter",
    headingFont: "'Merriweather', serif",
    bodyFont: "'Inter', sans-serif",
  },
  {
    id: "executive-serif",
    name: "Executive Editorial",
    description: "Lora + Inter",
    headingFont: "'Lora', serif",
    bodyFont: "'Inter', sans-serif",
  },
  {
    id: "technical-mono",
    name: "Technical Clean",
    description: "JetBrains Mono + Inter",
    headingFont: "'JetBrains Mono', monospace",
    bodyFont: "'Inter', sans-serif",
  },
  {
    id: "timeless-elegant",
    name: "Timeless Serif",
    description: "Cormorant Garamond + Lora",
    headingFont: "'Cormorant Garamond', serif",
    bodyFont: "'Lora', serif",
  },
];

export const DIVIDER_STYLES = [
  { id: "solid", name: "Solid Line" },
  { id: "hairline", name: "Subtle Hairline" },
  { id: "accent-bar", name: "Accent Bar" },
  { id: "dotted", name: "Dotted Rule" },
  { id: "double", name: "Double Rule" },
  { id: "none", name: "No Divider" },
];

export const HEADER_LAYOUTS = [
  { id: "centered", name: "Centered Formal" },
  { id: "left", name: "Left Aligned" },
  { id: "split", name: "Two-Column Split" },
  { id: "minimal", name: "Inline Minimal" },
];

export const DEFAULT_CUSTOMIZATION = {
  templateId: "modern",
  styleDirection: "modern",
  accentColor: "#4338ca",
  fontPairing: "modern-sans",
  fontSize: "standard", // "compact", "standard", "spacious"
  sectionSpacing: "standard", // "compact", "standard", "spacious"
  margins: "standard", // "compact", "standard", "generous"
  dividerStyle: "accent-bar",
  headerLayout: "split",
  showIcons: true,
  sectionOrder: ["summary", "skills", "projects", "experience", "achievements", "education"],
  visibleSections: {
    summary: true,
    skills: true,
    projects: true,
    experience: true,
    achievements: true,
    education: true,
  },
};
