export const API_ENDPOINTS = {
  LOGIN: "/api/v1/auth/login",
  LOGIN_REQUEST_OTP: "/api/v1/auth/login-request-otp",
  LOGIN_VERIFY_OTP: "/api/v1/auth/login-verify-otp",
  REGISTER: "/api/v1/auth/register",
  LOGOUT: "/api/v1/auth/logout",
  CURRENT_USER: "/api/v1/auth/me",

  USER_PROFILE: "/api/v1/users/profile",
  USER_CODING_PROFILES: "/api/v1/users/coding-profiles",
  SYNC_ACCOUNTS: "/api/v1/users/sync",
  SETTINGS: "/api/v1/users/settings",

  DASHBOARD: "/api/v1/dashboard",
  PROGRESS: "/api/v1/analytics/progress",
  SKILLS: "/api/v1/skills",
  PROJECTS: "/api/v1/projects",
  ACHIEVEMENTS: "/api/v1/achievements",
  RECOMMENDATIONS: "/api/v1/career/recommendations",
  LEADERBOARD: "/api/v1/leaderboard",
  CAREER_JOBS: "/api/v1/career/jobs",
  CAREER_LIVE_JOBS: "/api/v1/career/live-jobs",
  NOTIFICATIONS: "/api/v1/notifications",
  RESUME: "/api/v1/resume",
  RESUME_AI_REVIEW: "/api/v1/resume/ai-review",
  RESUME_AUTO_FILL: "/api/v1/resume/auto-fill",
  VERIFY_HANDLE: "/api/v1/dashboard/verify-handle",
  VERIFY_PLATFORM: "/api/v1/users/verify-platform",
  RECRUITER_CANDIDATES: "/api/v1/recruiter/candidates",
};

